# Generated by Django 3.2.7 on 2021-09-11 18:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Produto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=140)),
                ('categoria', models.CharField(max_length=140)),
                ('preco', models.CharField(max_length=140)),
            ],
            options={
                'ordering': ['nome'],
            },
        ),
    ]
